use_frameworks!

platform :ios, '10.0'

target 'FooLib_Example' do
  pod 'ACPCore', '~> 2.3'
  pod 'ACPAnalytics', '~> 2.1'
  pod 'NewRelicAgent'
  pod 'FooLib', :path => '../'

  target 'FooLib_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
